- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - release-notes-jobs
    check:
      jobs:
        - aodh-dsvm-tempest-plugin-mysql
        - aodh-dsvm-tempest-plugin-postgresql
        - telemetry-dsvm-integration
        - telemetry-tox-py37
    gate:
      jobs:
        - aodh-dsvm-tempest-plugin-mysql
        - aodh-dsvm-tempest-plugin-postgresql
        - telemetry-dsvm-integration
        - telemetry-tox-py37
    experimental:
      jobs:
        # TripleO jobs that deploy Telemetry.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario00(1|2)-multinode-oooq will only
        # run on stable/pike while the -container will run in Queens
        # and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        # NOTE(sileht): These job takes 3 hours and fail most of the times.
        # While other jobs take 20-30 minutes
        # We can reenable it when they take less times.
        - tripleo-ci-centos-7-scenario001-multinode-oooq
        - tripleo-ci-centos-7-scenario001-multinode-oooq-container
        - tripleo-ci-centos-7-scenario002-multinode-oooq
        - tripleo-ci-centos-7-scenario002-multinode-oooq-container

- job:
    name: aodh-dsvm-tempest-plugin-mysql
    parent: legacy-dsvm-base
    run: playbooks/legacy/aodh-dsvm-tempest-plugin-mysql/run.yaml
    post-run: playbooks/legacy/aodh-dsvm-tempest-plugin-mysql/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/aodh
      # To install Gnocchi
      - openstack/ceilometer
      - openstack/telemetry-tempest-plugin
      - openstack/tempest

- job:
    name: aodh-dsvm-tempest-plugin-postgresql
    parent: legacy-dsvm-base
    run: playbooks/legacy/aodh-dsvm-tempest-plugin-postgresql/run.yaml
    post-run: playbooks/legacy/aodh-dsvm-tempest-plugin-postgresql/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/aodh
      # To install Gnocchi
      - openstack/ceilometer
      - openstack/telemetry-tempest-plugin
      - openstack/tempest
